CREATE TABLE compute(
    id INT AUTO_INCREMENT PRIMARY KEY,
    x INT NOT NULL,
    y INT NOT NULL,
    r INT NOT NULL,
    ip VARCHAR(15) NOT NULL,
    ts DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);